### ISSUE TITLE
Fix 2xl-Breakpoint

### ISSUE THREAD

**Issue by kevludwig** [jonny-lake/tw-break#1]
2xl is now an official Tailwind-Breakpoint, but only "xl" is highlighted.

![image](https://user-images.githubusercontent.com/38694440/197343415-675c6adc-3273-44de-86c1-14ec9a6b98ec.png)

**Comment by jonthemonke** [comment]
I'll have that fixed right away!

**Comment by jonthemonke** [comment]
Just added support for 2xl in the latest update. Thanks for the feedback, let me know if you'd like any other functionality!
