### ISSUE TITLE
Support for PHP and Blade.php

### ISSUE THREAD

**Issue by danielzebini** [jonny-lake/tw-break#2]
Congratulations on the extension, I've been looking for it...
 
I'm on a project using Laravel .Blade.php and it doesn't work

Is there a possibility of support?

Thank you

**Comment by jonny-lake** [comment]
Sorry for the late response, I will get on this as soon as possible!

**Comment by jonthemonke** [comment]
@danielzebini I have updated to version 1.0.3 with support for *.php file extensions. Please let me know if this has fixed your issue.
